// The installer speaks like UwULock's default, playful tone, in German or English.

const de = {
  welcomeTitle: 'Hallo! Ich bin Nyu',
  welcomeBody: 'Ich richte UwULock in ein paar Sekunden auf deinem {computer} ein.',
  againTitle: 'Schön, dich wiederzusehen!',
  againBody:
    'UwULock {installed} ist schon da. Ich bringe es auf {version}, deine Anmeldung und deine Einstellungen bleiben, wo sie sind.',
  install: 'Installieren',
  update: 'Aktualisieren',
  reinstall: 'Neu installieren',
  options: 'Optionen',
  fewerOptions: 'Weniger Optionen',
  folder: 'Speicherort',
  change: 'Ändern …',
  desktopShortcut: 'Verknüpfung auf dem Desktop',
  runningTitle: 'UwULock ist gerade offen',
  runningBody:
    'Ich schließe es kurz, damit ich weitermachen kann. Dein Tresor wird dabei gesperrt.',
  closeAndContinue: 'Schließen und weiter',
  back: 'Zurück',
  progressInstall: 'Nyu richtet alles ein …',
  progressUpdate: 'Nyu bringt UwULock auf den neuesten Stand …',
  progressUninstall: 'Nyu räumt auf …',
  quotes: [
    'Ölt das Schloss …',
    'Poliert den Bügel …',
    'Zählt Sternchen …',
    'Mischt Zufallszahlen …',
    'Übt Ohrenwackeln …',
    'Sortiert Schlüssel …',
    'Versteckt Passwörter unterm Kissen …',
  ],
  doneTitle: 'Fertig! ✧',
  doneBody: 'UwULock ist bereit für deine Passwörter.',
  updateDoneTitle: 'Alles frisch! ✧',
  updateDoneBody: 'UwULock {version} startet gleich wieder.',
  tipsTitle: 'Kleine Tipps',
  tips: [
    'Schon ein Vaultwarden oder Bitwarden? Einfach mit deinem Konto anmelden.',
    'Strg+F sucht, Strg+L sperrt, Strg+G öffnet den Passwort-Generator.',
    'Stabil oder Beta? Den Update-Kanal wählst du in den Einstellungen.',
  ],
  start: 'UwULock starten',
  close: 'Schließen',
  errorTitle: 'Hoppla, das hat nicht geklappt',
  retry: 'Nochmal versuchen',
  uninstallTitle: 'Schade, dass du gehst …',
  uninstallBody: 'Ich entferne UwULock von diesem {computer}.',
  removeInstead: 'Deinstallieren …',
  computerWindows: 'PC',
  computerMac: 'Mac',
  computerLinux: 'Rechner',
  keepData: 'Anmeldung und Einstellungen behalten',
  keepDataHint:
    'Praktisch, falls du wiederkommst. Sonst lösche ich auch die verschlüsselte Kopie deines Tresors von diesem Gerät – auf dem Server bleibt er, wie er ist.',
  uninstall: 'Deinstallieren',
  keep: 'Doch behalten',
  goodbyeTitle: 'Tschüss! (｡•́︿•̀｡)',
  goodbyeBody: 'UwULock ist entfernt. Komm gern wieder vorbei.',
  soundOn: 'Ton an',
  soundOff: 'Ton aus',
  minimize: 'Minimieren',
  devBuild: 'Entwicklungs-Build: UwULock ist hier nicht mit drin.',
  sandbox: 'Testmodus: Es wird nur in einem Testordner installiert.',
  footer: 'Version {version} · Open Source',
};

const en: typeof de = {
  welcomeTitle: "Hi! I'm Nyu",
  welcomeBody: "I'll set up UwULock on your {computer} in a few seconds.",
  againTitle: 'Nice to see you again!',
  againBody:
    "UwULock {installed} is already here. I'll bring it to {version}, and your login and settings stay where they are.",
  install: 'Install',
  update: 'Update',
  reinstall: 'Reinstall',
  options: 'Options',
  fewerOptions: 'Fewer options',
  folder: 'Location',
  change: 'Change …',
  desktopShortcut: 'Shortcut on the desktop',
  runningTitle: 'UwULock is open right now',
  runningBody: "I'll close it for a moment so I can carry on. Your vault gets locked.",
  closeAndContinue: 'Close and continue',
  back: 'Back',
  progressInstall: 'Nyu is setting everything up …',
  progressUpdate: 'Nyu is bringing UwULock up to date …',
  progressUninstall: 'Nyu is tidying up …',
  quotes: [
    'Oiling the lock …',
    'Polishing the shackle …',
    'Counting asterisks …',
    'Shuffling random numbers …',
    'Practicing ear wiggles …',
    'Sorting keys …',
    'Hiding passwords under the pillow …',
  ],
  doneTitle: 'All done! ✧',
  doneBody: 'UwULock is ready for your passwords.',
  updateDoneTitle: 'All fresh! ✧',
  updateDoneBody: 'UwULock {version} starts again in a moment.',
  tipsTitle: 'Little tips',
  tips: [
    'Already on Vaultwarden or Bitwarden? Just log in with your account.',
    'Ctrl+F searches, Ctrl+L locks, Ctrl+G opens the password generator.',
    'Stable or Beta? Pick the update channel in the settings.',
  ],
  start: 'Start UwULock',
  close: 'Close',
  errorTitle: "Oops, that didn't work",
  retry: 'Try again',
  uninstallTitle: 'Sad to see you go …',
  uninstallBody: "I'll remove UwULock from this {computer}.",
  removeInstead: 'Uninstall …',
  computerWindows: 'PC',
  computerMac: 'Mac',
  computerLinux: 'computer',
  keepData: 'Keep login and settings',
  keepDataHint:
    'Handy if you come back. Otherwise I also delete the encrypted copy of your vault on this device – on the server it stays as it is.',
  uninstall: 'Uninstall',
  keep: 'Keep it',
  goodbyeTitle: 'Bye! (｡•́︿•̀｡)',
  goodbyeBody: 'UwULock is removed. Come back any time.',
  soundOn: 'Sound on',
  soundOff: 'Sound off',
  minimize: 'Minimize',
  devBuild: "Development build: UwULock isn't packed inside.",
  sandbox: 'Test mode: installs into a test folder only.',
  footer: 'Version {version} · Open source',
};

export type Texts = typeof de;

export const texts: Texts = navigator.language.toLowerCase().startsWith('de') ? de : en;

export function fill(template: string, values: Record<string, string>) {
  return template.replace(/\{(\w+)\}/g, (_, key: string) => values[key] ?? '');
}
